scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ["prometheus"]
    scheme: https
    authorization:
      credentials_file: /etc/prometheus/prometheus-token
    static_configs:
      - targets: ["10.1.42.101:8200"]
    tls_config:
      insecure_skip_verify: true
